services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gg71_app
    ports:
      - "3000:3000"
    volumes:
      - .:/app                # Mount local code
      - /app/node_modules     # Keep container's node_modules safe
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/garagegrid
      - NEXT_TELEMETRY_DISABLED=1
    command: pnpm dev         # run dev server instead of build
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garagegrid
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - "8080:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - db

volumes:
  pgdata:
